#!/bin/bash

DIR="$HOME/Personal_BH/Maintenance"
FILE="bfind.py"
FIL="bfind"        # for quick use on command line
CONF="bfind.conf"
#
#
echo "Deploying bfind"

# copy both versions to reference bin copy for restoration or mass upgrade
cp $FILE   "$DIR/bin"
chmod 755  "$DIR/bin/$FILE"
cp "$FILE" "$DIR/bin/$FIL"
chmod 755  "$DIR/bin/$FIL"

# update the local machine's ~/bin
cp "$FILE"    "$HOME/bin/$FILE"
chmod 755     "$HOME/bin/$FILE"
cp ./"$FILE"  "$HOME/bin/$FIL"
chmod  755    "$HOME/bin/$FIL"

# update .conf file
cp ./"$CONF"   ~/"$CONF"
